export const DOCUMENT_TYPE_MISMATCH_CODE = "DOCUMENT_TYPE_MISMATCH" as const;
export const FORBIDDEN_CODE = "FORBIDDEN" as const;
export const IDEMPOTENCY_CONFLICT_CODE = "IDEMPOTENCY_CONFLICT" as const;
export const INTERNAL_ERROR_CODE = "INTERNAL_ERROR" as const;
export const INVALID_REQUEST_CODE = "INVALID_REQUEST" as const;
export const LINE_TOTAL_MISMATCH_CODE = "LINE_TOTAL_MISMATCH" as const;
export const NOT_FOUND_CODE = "NOT_FOUND" as const;
export const QUOTA_EXCEEDED_CODE = "QUOTA_EXCEEDED" as const;
export const RATE_LIMITED_CODE = "RATE_LIMITED" as const;
export const TAX_TOTAL_MISMATCH_CODE = "TAX_TOTAL_MISMATCH" as const;
export const UNAUTHORIZED_CODE = "UNAUTHORIZED" as const;
export const UNSUPPORTED_SCHEMA_VERSION_CODE =
	"UNSUPPORTED_SCHEMA_VERSION" as const;
export const VALIDATION_FAILED_CODE = "VALIDATION_FAILED" as const;
export const WORKSPACE_REQUIRED_CODE = "WORKSPACE_REQUIRED" as const;

export const ERROR_CODES = [
	"DOCUMENT_TYPE_MISMATCH",
	"FORBIDDEN",
	"IDEMPOTENCY_CONFLICT",
	"INTERNAL_ERROR",
	"INVALID_REQUEST",
	"LINE_TOTAL_MISMATCH",
	"NOT_FOUND",
	"QUOTA_EXCEEDED",
	"RATE_LIMITED",
	"TAX_TOTAL_MISMATCH",
	"UNAUTHORIZED",
	"UNSUPPORTED_SCHEMA_VERSION",
	"VALIDATION_FAILED",
	"WORKSPACE_REQUIRED",
] as const;

export type ErrorCode = (typeof ERROR_CODES)[number];
