import type { ErrorCode } from "./codes";

const ERROR_CODE_HTTP_STATUS: Record<ErrorCode, number> = {
	DOCUMENT_TYPE_MISMATCH: 400,
	FORBIDDEN: 403,
	IDEMPOTENCY_CONFLICT: 409,
	INTERNAL_ERROR: 500,
	INVALID_REQUEST: 400,
	LINE_TOTAL_MISMATCH: 422,
	NOT_FOUND: 404,
	QUOTA_EXCEEDED: 402,
	RATE_LIMITED: 429,
	TAX_TOTAL_MISMATCH: 422,
	UNAUTHORIZED: 401,
	UNSUPPORTED_SCHEMA_VERSION: 400,
	VALIDATION_FAILED: 422,
	WORKSPACE_REQUIRED: 403,
};

export function getHttpStatusForErrorCode(code: ErrorCode): number {
	return ERROR_CODE_HTTP_STATUS[code];
}
